### ISSUE TITLE
Use Lotus::Validations instead of Virtus.model (?)

### ISSUE THREAD

**Issue by katafrakt** [PuzzleFlow/tochtli#3]
Some time ago we decided to put `Virtus.model` instead of `ActiveModel` for messages and their attributes. However, there is one kid on the block that we forgot to evaluate. And that is, as you might already suspect, `Lotus::Validations`. You can read more about it [here](https://github.com/lotus/validations).

What we get? Most important is, probably, validations, which are lost with introduction of `Virtus`. As far as I remember we only have now some pseudovalidation of attribute's presence. With `Lotus::Validations` we would get more or less fully fledged validations without losing `Virtus`'s power, i.e. coercions (mostly).

I probably could try to prepare a branch with `Lotus::Validations` instad of `Virtus.model` if we agree that this is a direction we want to pursue.

**Comment by rafalbigaj** [comment]
Looks promising. I forgot about `Lotus`. The leak of real validations could be a problem in the future.

Feel free and go on with the new branch. Are you able to specify the timeframe for this task?

**Comment by katafrakt** [comment]
It's really hard to say but maybe I will be able to do it until the end of next week.

**Comment by rafalbigaj** [comment]
I was also intensively thinking about JSON Schema, but see no way using coercion with it. JSON Schema validator is perfect for our needs, but how to coerce for ex. datetime values (or embedded objects). There is no such functionality.

Any ideas?

**Comment by katafrakt** [comment]
First working (passing tests) version is in lotus-validations branch: https://github.com/PuzzleFlow/tochtli/tree/lotus-validations Still needs some further look on it but I'd welcome any comments already.

**Comment by rafalbigaj** [comment]
Lotus coercions are poor in comparison to the Virtus model. There are no default values and collections (see https://discuss.lotusrb.org/t/allow-lotus-validations-to-coerce-members-of-an-array/120). We already use such features. Therefore I see no chance to use Lotus for now. :(

Rich coercions are more valuable then validations.

**Comment by katafrakt** [comment]
OK, but I'm a bit worried about Virtus's future: https://twitter.com/_solnic_/status/631408414468538368

**Comment by rafalbigaj** [comment]
That's sad. We'll see.
